# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '___PROJECTNAME___' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ___PROJECTNAME___
  pod 'Alamofire'

  target '___PROJECTNAME___Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target '___PROJECTNAME___UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
